apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-aepc-ms-config-service
  labels:
    app: k8s-aepc-ms-config-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-aepc-ms-config-service
  template:
    metadata:
      name: k8s-aepc-ms-config-service
      labels:
        app: k8s-aepc-ms-config-service
    spec:
      containers:
        - name: k8s-aepc-ms-config-service
          image: placidenduwayo1/k8s-aepc-ms-config-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8280
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-aepc-ms-config-service
  labels:
    app: k8s-aepc-ms-config-service
spec:
  selector:
    app: k8s-aepc-ms-config-service
  ports:
    - protocol: TCP
      port: 8280
      targetPort: 8280
      name: 8280-8280
      nodePort: 30280
  type: LoadBalancer