# Here a pc is a Deployment, a pc has a unique IP Address,
#  here the IP Address refers to a service
apiVersion: apps/v1
kind: Deployment # a deployment
metadata:
  name: k8s-ms-config-deploy
  labels:
    app: k8s-aepc-ms-config-pod
spec:
  selector:
    matchLabels:
      app: k8s-aepc-ms-config-pod # pod related to this deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-aepc-ms-config-pod
    spec:
      containers:
        - name: k8s-aepc-ms-config-server
          image: placidenduwayo1/k8s-aepc-ms-config-server
          ports:
            - containerPort: 8280
---
# service associated to pc
apiVersion: v1
kind: Service
metadata:
  name: k8s-aepc-ms-config-svc
  labels:
    app: ms-config-svc
spec:
  ports:
    - port: 8280
      targetPort: 8280
      protocol: TCP
  type: LoadBalancer
  selector:
    app : k8s-aepc-ms-config-pod