apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-aepc-ms-registry-deploy
  labels:
    app: k8s-aepc-ms-registry-pod
spec:
  selector:
    matchLabels:
      app: k8s-aepc-ms-registry-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-aepc-ms-registry-pod
    spec:
      containers:
        - name: k8s-aepc-ms-registry
          image: placidenduwayo1/k8s-aepc-ms-registry
          ports:
            - containerPort: 8761

---
# service part
apiVersion: v1
kind: Service
metadata:
  name: k8s-aepc-ms-registry-svc
  labels:
    app: ms-registry-svc
spec:
  selector:
    app: k8s-aepc-ms-registry-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761