apiVersion: v1
kind: Service
metadata:
  name: k8s-aepc-bs-ms-employee-svc
  labels:
    app: ms-employee-svc
spec:
  ports:
    - port: 8283
      targetPort: 8283
  type: LoadBalancer
  selector:
    app: k8s-aepc-bs-ms-employee-pod
