apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-eapc-bs-ms-address-deploy
  labels:
    app: k8s-aepc-bs-ms-address-pod
spec:
  selector:
    matchLabels:
      app: k8s-aepc-bs-ms-address-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-aepc-bs-ms-address-pod
    spec:
      containers:
        - name: k8s-aepc-bs-ms-address
          image: placidenduwayo1/k8s-aepc-bs-ms-address
          ports:
            - containerPort: 8282