apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-aepc-db-service
  labels:
    app: k8s-aepc-db-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-aepc-db-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s-aepc-db-service
    spec:
      containers:
      - name: k8s-aepc-db-service
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-root-mdp
                name: mysql-db-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: k8s-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-aepc-db-service
  labels:
    app: k8s-aepc-db-service
spec:
  selector:
    app: k8s-aepc-db-service
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP