apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-aepc-bs-ms-project-deploy
  labels:
    app: k8s-aepc-bs-ms-project-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-aepc-bs-ms-project-pod
  template:
    metadata:
      labels:
        app: k8s-aepc-bs-ms-project-pod
    spec:
      containers:
        - name: k8s-aepc-bs-ms-project
          image: placidenduwayo1/k8s-aepc-bs-ms-project
          ports:
            - containerPort: 8285